# Generated by Django 4.1.3 on 2022-11-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.PositiveIntegerField(default=0, verbose_name='Start Point')),
                ('end_point', models.PositiveIntegerField(default=0, verbose_name='End Point')),
                ('string', models.CharField(max_length=100, verbose_name='String')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Createed Date Time')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
